[package]
name = "cddl"
description = "Parser for the Concise data definition language (CDDL)"
repository = "https://github.com/anweiss/cddl"
license = "MIT"
version = "0.3.8"
authors = ["Andrew Weiss <andrew.weiss@outlook.com>"]
readme = "README.md"
edition = "2018"

[dependencies]
serde_json = { version = "1.0", optional = true, default-features = false }
serde_cbor = { version = "0.10", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }
crossterm = "0.9"
half = "1.3"
lexical-core = "^0.4"
clap = "2.33"
base16 = "0.2"
base64 = "0.10"
regex = "1.2"

[features]
default = ["std"]
std = ["serde_json", "serde_cbor", "serde"]

[[bin]]
name = "cddl"
required-features = ["std"]

[[bin]]
name = "repl"
required-features = ["std"]

[badges]
azure-devops = { project = "anweiss/cddl", pipeline = "cddl-CI", build = "1" }
codecov = { repository = "anweiss/cddl", branch = "master", service = "github" }