[package]
name = "cddl"
description = "Parser for the Concise data definition language (CDDL)"
repository = "https://github.com/anweiss/cddl"
homepage = "https://cddl.anweiss.tech"
license = "MIT"
version = "0.5.6"
authors = ["Andrew Weiss <andrew.weiss@outlook.com>"]
readme = "README.md"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base16 = "0.2"
base64 = "0.12"
codespan-reporting = "0.9"
itertools = "0.9"
lexical = "^5.1"
chrono = { version = "0.4", optional = true }
clap = { version = "2.33", optional = true }
regex = { version = "1.3", default-features = false, features = ["std"] }
serde = { version = "1.0", optional = true, features = ["derive"] }
serde_json = { version = "1.0", optional = true, default-features = false }
serde_cbor = { version = "0.11", optional = true }
uriparse = { version = "0.6", optional = true }

[dev-dependencies]
indoc = "0.3"
pretty_assertions = { git = "https://github.com/colin-kiegel/rust-pretty-assertions" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
crossterm = { version = "0.17", optional = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = { version = "0.1", optional = true }
wasm-bindgen = { version = "0.2", features = ["serde-serialize"], optional = true }
wee_alloc = { version = "0.4", optional = true }

[target.'cfg(target_arch = "wasm32")'.dev-dependencies]
wasm-bindgen-test = "0.3"

[features]
default = ["std"]
std = ["serde_json", "serde_cbor", "serde", "chrono", "wasm-bindgen", "clap", "crossterm"]
nightly = ["uriparse"]

[[bin]]
name = "cddl"
required-features = ["std"]
path = "src/bin/cddl.rs"

[[bin]]
name = "repl"
required-features = ["std"]
path = "src/bin/repl.rs"

[profile.release]
opt-level = "s"
lto = true
