[package]
name = "cddl"
description = "Parser for the Concise data definition language (CDDL)"
repository = "https://github.com/anweiss/cddl"
license = "MIT"
version = "0.2.0"
authors = ["Andrew Weiss <andrew.weiss@outlook.com>"]
edition = "2018"


[dependencies]
serde_json = "1.0"
crossterm = "0.9"
half = "1.3"
lexical-core = "^0.4"

[features]
default = ["std"]
std = []