export const standardPrelude = [
	{ label: "any", detail: "any data type" },
	{ label: "uint", detail: "unsigned integer" },
	{ label: "nint", detail: "negative integer" },
	{ label: "int", detail: "integer" },
	{ label: "bstr", detail: "byte string" },
	{ label: "bytes", detail: "byte string; alias for bstr" },
	{ label: "tstr", detail: "text string" },
	{ label: "text", detail: "text string, alias for tstr" },
	{ label: "tdate", detail: "date/time strings" },
	{ label: "time", detail: "time in seconds relative to UNIX epoch" },
	{ label: "number", detail: "integer or floating point number" },
	{ label: "biguint", detail: "large unsigned integer encoded as a byte string" },
	{ label: "bignint", detail: "large negative integer encoded as a byte string" },
	{ label: "bigint", detail: "large integer encoded as a byte string" },
	{ label: "integer", detail: "alias for int or bigint" },
	{ label: "unsigned", detail: "alias for uint or biguint" },
	{ label: "decfrac", detail: "decimal fraction" },
	{ label: "bigfloat", detail: "bitfloat" },
	{ label: "eb64url", detail: "expected conversion of byte string to base64url-encoded text string" },
	{ label: "eb64legacy", detail: "expected conversion of byte string to base64-encoded text string" },
	{ label: "eb16", detail: "expected conversion of byte string to base16-encoded text string" },
	{ label: "encoded-cbor", detail: "embedded CBOR data item" },
	{ label: "uri", detail: "URI text string" },
	{ label: "b64url", detail: "base64url-encoded text string" },
	{ label: "b64legacy", detail: "base64-encoded text string" },
	{ label: "regexp", detail: "regular expression in PCRE or JavaScript syntax" },
	{ label: "mime-message", detail: "MIME message, including all headers" },
	{ label: "cbor-any", detail: "self-described CBOR" },
	{ label: "float16", detail: "16-bit floating point value" },
	{ label: "float32", detail: "32-bit floating point value" },
	{ label: "float64", detail: "64-bit floating point value" },
	{ label: "float16-32", detail: "16- or 32-bit floating point value" },
	{ label: "float32-64", detail: "32- or 64-bit floating point value" },
	{ label: "float", detail: "floating point value" },
	{ label: "false", detail: "false" },
	{ label: "true", detail: "true" },
	{ label: "bool", detail: "boolean" },
	{ label: "nil", detail: "null value" },
	{ label: "null", detail: "null value; alias for nil" },
	{ label: "undefined", detail: "undefined value" }
];